# https://github.com/actions/stale
name: Obsolete Issues

on:
  workflow_dispatch:
  schedule:
  - cron: '0 10 1,15 * *'

jobs:
  obsolete-issues:

    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - name: Track stale issues and check if obsolete
      uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-issue-stale: 0
        stale-issue-message: >
          This issue is marked as obsolete due to inactivity for last 0 days. 
          To avoid issue getting closed in next 30 days, please add a comment or add 'awaiting-maintainer' label. Thank you for your contributions
        stale-issue-label: 'obsolete'
        only-labels: 'stale'
        exempt-issue-labels: awaiting-maintainer
        #labels-to-remove-when-stale: 'stale'
        remove-stale-when-updated: true
        ascending: true
        days-before-close: -1
        enable-statistics: true
    
    - name: Remove stale label
        uses: octokit/rest.js@v5.x
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          const { data: labels } = await octokit.issues.listLabelsOnIssue({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          const staleLabel = labels.find((label) => label.name === 'stale');
          if (staleLabel) {
            await octokit.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'stale',
            });
          }
